global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Eureka Server
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']
        labels:
          application: 'eureka-server'
          environment: 'development'

  # API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          application: 'api-gateway'
          environment: 'development'

  # User Service
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']
        labels:
          application: 'user-service'
          environment: 'development'

  # TODO Service
  - job_name: 'todo-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['todo-service:8082']
        labels:
          application: 'todo-service'
          environment: 'development'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']