version: '3.8'

services:
  # Seulement les bases de données pour le développement local
  postgres-user:
    image: postgres:15-alpine
    container_name: postgres-user-dev
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-user-dev-data:/var/lib/postgresql/data

  postgres-todo:
    image: postgres:15-alpine
    container_name: postgres-todo-dev
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-todo-dev-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"

  # Monitoring (optionnel en dev)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-dev
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-dev
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres-user-dev-data:
  postgres-todo-dev-data: