name: Backend Build & Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    name: Build & Test Backend
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name:  Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java 17
      - name:  Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Build shared-lib en premier
      - name:  Build Shared Library
        working-directory: ./backend/shared-lib
        run: mvn clean install -DskipTests

      # 4. Build tous les services
      - name:  Build All Services
        working-directory: ./backend
        run: mvn clean package -DskipTests

      # 5. Run tests
      - name:  Run Tests
        working-directory: ./backend
        run: mvn test

      # 6. Upload artifacts
      - name:  Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-jars
          path: |
            backend/*/target/*.jar
          retention-days: 7